"""Add content embeddings table for semantic similarity.

Revision ID: 002_embeddings
Revises: 001_privacy
Create Date: 2026-01-13

This migration adds the content_embeddings table for storing
embedding vectors generated by Ollama (nomic-embed-text model).
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "002_embeddings"
down_revision: Union[str, Sequence[str], None] = "001_privacy"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add content_embeddings table."""
    op.create_table(
        "content_embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "content_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "embedding",
            postgresql.ARRAY(sa.Float()),
            nullable=False,
        ),
        sa.Column("model", sa.String(100), nullable=False, server_default="nomic-embed-text"),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.text("NOW()")),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.text("NOW()")),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["content_items.id"],
            ondelete="CASCADE",
        ),
    )

    # Create unique index on content_id
    op.create_index(
        "ix_content_embeddings_content_id",
        "content_embeddings",
        ["content_id"],
        unique=True,
    )


def downgrade() -> None:
    """Remove content_embeddings table."""
    op.drop_index("ix_content_embeddings_content_id", table_name="content_embeddings")
    op.drop_table("content_embeddings")
